services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    command: npm run dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
